/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.healthathome.api;

import io.healthathome.dto.Order;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-03-08T15:45:56.178Z")

@Api(value = "order", description = "the order API")
public interface OrderApi {

    @ApiOperation(value = "order", notes = "", response = List.class, responseContainer = "List", authorizations = {
        @Authorization(value = "Bearer")
    }, tags={ "order", })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "successful operation", response = List.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized", response = Void.class) })

    @RequestMapping(value = "/order/user/{user}",
        produces = { "application/json" },
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<String>> getOrdersByUser(@ApiParam(value = "User ID", required = true) @PathVariable("user") String user);

    @ApiOperation(value = "order", notes = "", response = Order.class, responseContainer = "List", authorizations = {
            @Authorization(value = "Bearer")
    }, tags={ "order", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation", response = Order.class, responseContainer = "List"),
            @ApiResponse(code = 401, message = "Unauthorized", response = Void.class) })

    @RequestMapping(value = "/order/{idOrder}",
            produces = { "application/json" },
            consumes = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<Order> getOrder(@ApiParam(value = "Order ID", required = true) @PathVariable("idOrder") String idOrder);

}
